apiVersion: batch/v1
kind: Job
metadata:
  generateName: db-migrate-
  namespace: salon-app
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-postgres
          image: postgres:17
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: salon-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: salon-secrets
                  key: POSTGRES_DB
          command:
            - sh
            - -c
            - |
              echo "Waiting for PostgreSQL..."

              until pg_isready \
                -h postgres-svc \
                -p 5432 \
                -U "$POSTGRES_USER" \
                -d "$POSTGRES_DB"
              do
                echo "PostgreSQL is not ready..."
                sleep 2
              done

              echo "PostgreSQL is ready."
      containers:
        - name: db-migrate
          image: dev7878/lumiere-salon-dbtools:de4e0f53d10758bc938d115e0c70c6c95f1aba6a
          imagePullPolicy: Always
          command:
            - npx
            - prisma
            - migrate
            - deploy
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: salon-secrets
                  key: DATABASE_URL
