name: Salon App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:  

jobs:

# test job 
  test:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432          
    env:
      DATABASE_URL: postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASS }}@localhost:5432/${{ secrets.DB_NAME }}?schema=public
      SESSION_SECRET: ""

    steps:
      - name: Code Checlout
        uses:  actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
           node-version: "20"
           cache: "npm"

      - name: Install Dependecies    
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Run unit Test
        run: npm run test

      - name: Apply Schema to the test db
        run: npx prisma db push

      - name: Run integration tests
        run: npm run test:integration    

# build job

  build:
    needs: test
    runs-on: ubuntu-22.04
    env:
      IMAGE_TAG: ${{ github.sha }}
      IMAGE_NAME: lumiere-salon
      IMAGE_NAME_2: lumiere-salon-dbtools  
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      -
        name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
     
      - name: Build The Image SALON-APP
        run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG .
      
      - name: Build The Image DBTOOL
        run: docker build -f Dockerfile.dbtools -t ${{ vars.DOCKERHUB_USERNAME }}/$IMAGE_NAME_2:$IMAGE_TAG .

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@e07451d2e059ed86c2870430ea286b3a9e0bf241
        with:
          cache: true

      - name: Run Trivy vulnerability scan SALON-APP
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: 'table'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          output: 'trivy-report.txt'

      - name: Run Trivy vulnerability scan DBTOOL-IMAGE 
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME_2 }}:${{ env.IMAGE_TAG }}
          format: 'table'
          exit-code: '1'   
          severity: 'HIGH,CRITICAL'
          trivyignores: '.trivyignore'
          output: 'trivy-report-2.txt'   

      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: trivy-report
          path: trivy-report*.txt
          if-no-files-found: error

      - name: Docker PUSH IMAGE SALON-APP
        if: success()
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG

      - name: Docker PUSH IMAGE 2 DBTOOLS
        if: success()
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/$IMAGE_NAME_2:$IMAGE_TAG    

# k8s-manifest-update in yaml file

  k8s-manifest-update:
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Install YQ
        uses: mikefarah/yq@v4

      - name: Update imagetag in k8s rollout manifest
        run: |
          yq -ei '.spec.template.spec.containers[0].image |= sub(":.*", ":" + strenv(IMAGE_TAG))' k8s/rollout.yaml

      - name: Update image tag in k8s migrate-job manifest
        run: |
          yq -ei '.spec.template.spec.containers[0].image |= sub(":.*", ":" + strenv(IMAGE_TAG))' k8s/migrate-job.yaml

      - name: Update imagetag in k8s seed-job manifest
        run: |
          yq -ei '.spec.template.spec.containers[0].image |= sub(":.*", ":" + strenv(IMAGE_TAG))' k8s/seed-job.yaml
      
      - name: Commit Kubernetes manifest changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add k8s/rollout.yaml
          git add k8s/migrate-job.yaml
          git add k8s/seed-job.yaml

          git commit -m "ci: Update image tags to ${IMAGE_TAG}" || echo "No changes to commit"
          git push 

